pipeline{
   agent any

   environment{
        def myString = "Hello"
        def myNumber = 10
        def myBool = true
   }

   stages{
        stage("Demo"){
            steps{
                script {
                    if(myBool) {
                        echo "Yes"
                    }
                    else{
                        echo "No"
                    }
                }
                echo "Build Number: ${env.BUILD_NUMBER}"
                echo "myString value: ${myString}"
                echo "mynumber value: ${myNumber}"
                echo "mybool value: ${myBool}"
                myFunc("Hello World!")
            }
        }

        stage("Another job"){
            steps{
                build job: 'parameterized_Pipeline', parameters: [[$class: 'BooleanParameterValue', name:'DEBUG_BUILD', value:False]]
            }
        }
   }
}

def myFunc(String myText){
    echo "My text is : ${myText}"
}