pipeline{
    agent any
    stages{
        stage("Clean Dir"){
            steps{
                deleteDir()
            }
        }
        stage("stage 1"){
            steps{
                echo "This is stage 1"
                sh "echo 'hiehllo' > test.txt"
            }
        }
    }
    post {
        always{
            echo "${JOB_NAME}"
            sh """whoami
                  ls /var/jenkins_home/workspace/${JOB_NAME}"""
            cleanWs()
            sh "ls /var/jenkins_home/workspace/${JOB_NAME}"
        }
    }
}